import os
input("Press enter to run Q5")
os.system('python Q5.py')
input("Press enter to run Q6")
os.system('python Q6.py')
input("Press enter to run Q7")
os.system('python Q7.py')
input("Press enter to run Q10")
os.system('python Q10.py')
input("Press enter to run Q11")
os.system('python Q11.py')